runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
health_check:
  enable_health_check: False
  check_interval_sec: 60
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.11.4"
  disk_size_gb: 40
